<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: toba.gmtool.cs.proto

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>MSG_GetServerOnline_Respone</code>
 */
class MSG_GetServerOnline_Respone extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>.ERRNO result = 1;</code>
     */
    private $result = 0;
    /**
     * 服务器名
     *
     * Generated from protobuf field <code>string serverName = 2;</code>
     */
    private $serverName = '';
    /**
     * 在线玩家人数
     *
     * Generated from protobuf field <code>uint32 onlineCount = 3;</code>
     */
    private $onlineCount = 0;

    public function __construct() {
        \GPBMetadata\TobaGmtoolCs::initOnce();
        parent::__construct();
    }

    /**
     * Generated from protobuf field <code>.ERRNO result = 1;</code>
     * @return int
     */
    public function getResult()
    {
        return $this->result;
    }

    /**
     * Generated from protobuf field <code>.ERRNO result = 1;</code>
     * @param int $var
     * @return $this
     */
    public function setResult($var)
    {
        GPBUtil::checkEnum($var, \ERRNO::class);
        $this->result = $var;

        return $this;
    }

    /**
     * 服务器名
     *
     * Generated from protobuf field <code>string serverName = 2;</code>
     * @return string
     */
    public function getServerName()
    {
        return $this->serverName;
    }

    /**
     * 服务器名
     *
     * Generated from protobuf field <code>string serverName = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setServerName($var)
    {
        GPBUtil::checkString($var, True);
        $this->serverName = $var;

        return $this;
    }

    /**
     * 在线玩家人数
     *
     * Generated from protobuf field <code>uint32 onlineCount = 3;</code>
     * @return int
     */
    public function getOnlineCount()
    {
        return $this->onlineCount;
    }

    /**
     * 在线玩家人数
     *
     * Generated from protobuf field <code>uint32 onlineCount = 3;</code>
     * @param int $var
     * @return $this
     */
    public function setOnlineCount($var)
    {
        GPBUtil::checkUint32($var);
        $this->onlineCount = $var;

        return $this;
    }

}

