<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: toba.gmtool.cs.proto

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>MSG_GetServerList_Respone</code>
 */
class MSG_GetServerList_Respone extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>.ERRNO result = 1;</code>
     */
    private $result = 0;
    /**
     * 服务器列表
     *
     * Generated from protobuf field <code>repeated string serverList = 2;</code>
     */
    private $serverList;

    public function __construct() {
        \GPBMetadata\TobaGmtoolCs::initOnce();
        parent::__construct();
    }

    /**
     * Generated from protobuf field <code>.ERRNO result = 1;</code>
     * @return int
     */
    public function getResult()
    {
        return $this->result;
    }

    /**
     * Generated from protobuf field <code>.ERRNO result = 1;</code>
     * @param int $var
     * @return $this
     */
    public function setResult($var)
    {
        GPBUtil::checkEnum($var, \ERRNO::class);
        $this->result = $var;

        return $this;
    }

    /**
     * 服务器列表
     *
     * Generated from protobuf field <code>repeated string serverList = 2;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getServerList()
    {
        return $this->serverList;
    }

    /**
     * 服务器列表
     *
     * Generated from protobuf field <code>repeated string serverList = 2;</code>
     * @param string[]|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setServerList($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::STRING);
        $this->serverList = $arr;

        return $this;
    }

}

