<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: TSProtocol.proto

/**
 * Protobuf enum <code>MSG</code>
 */
class MSG
{
    /**
     * Generated from protobuf enum <code>MSGID_ZERO = 0;</code>
     */
    const MSGID_ZERO = 0;
    /**
     * Generated from protobuf enum <code>MSGID_Tool_Onlines_Request = 10001;</code>
     */
    const MSGID_Tool_Onlines_Request = 10001;
    /**
     * Generated from protobuf enum <code>MSGID_Tool_Onlines_Response = 20001;</code>
     */
    const MSGID_Tool_Onlines_Response = 20001;
    /**
     * Generated from protobuf enum <code>MSGID_Tool_Freezn_Request = 10002;</code>
     */
    const MSGID_Tool_Freezn_Request = 10002;
    /**
     * Generated from protobuf enum <code>MSGID_Tool_Freezn_Response = 20002;</code>
     */
    const MSGID_Tool_Freezn_Response = 20002;
    /**
     * Generated from protobuf enum <code>MSGID_Tool_UnFreezn_Request = 10003;</code>
     */
    const MSGID_Tool_UnFreezn_Request = 10003;
    /**
     * Generated from protobuf enum <code>MSGID_Tool_UnFreezn_Response = 20003;</code>
     */
    const MSGID_Tool_UnFreezn_Response = 20003;
    /**
     * Generated from protobuf enum <code>MSGID_Tool_Mail_Request = 10004;</code>
     */
    const MSGID_Tool_Mail_Request = 10004;
    /**
     * Generated from protobuf enum <code>MSGID_Tool_Mail_Response = 20004;</code>
     */
    const MSGID_Tool_Mail_Response = 20004;
}

