<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: TSProtocol.proto

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>MSG_Tool_Freezn_Request</code>
 */
class MSG_Tool_Freezn_Request extends \Google\Protobuf\Internal\Message
{
    /**
     *账号id	
     *
     * Generated from protobuf field <code>uint32 account_id = 1;</code>
     */
    private $account_id = 0;
    /**
     *解封时间		
     *
     * Generated from protobuf field <code>uint32 unfreezn = 2;</code>
     */
    private $unfreezn = 0;

    public function __construct() {
        \GPBMetadata\TSProtocol::initOnce();
        parent::__construct();
    }

    /**
     *账号id	
     *
     * Generated from protobuf field <code>uint32 account_id = 1;</code>
     * @return int
     */
    public function getAccountId()
    {
        return $this->account_id;
    }

    /**
     *账号id	
     *
     * Generated from protobuf field <code>uint32 account_id = 1;</code>
     * @param int $var
     * @return $this
     */
    public function setAccountId($var)
    {
        GPBUtil::checkUint32($var);
        $this->account_id = $var;

        return $this;
    }

    /**
     *解封时间		
     *
     * Generated from protobuf field <code>uint32 unfreezn = 2;</code>
     * @return int
     */
    public function getUnfreezn()
    {
        return $this->unfreezn;
    }

    /**
     *解封时间		
     *
     * Generated from protobuf field <code>uint32 unfreezn = 2;</code>
     * @param int $var
     * @return $this
     */
    public function setUnfreezn($var)
    {
        GPBUtil::checkUint32($var);
        $this->unfreezn = $var;

        return $this;
    }

}

