<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: toba.gmtool.cs.proto

namespace Toba\Gmtool\Cs;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * 获取服务器列表
 *
 * Generated from protobuf message <code>toba.gmtool.cs.MSG_GetServerList_Request</code>
 */
class MSG_GetServerList_Request extends \Google\Protobuf\Internal\Message
{

    public function __construct() {
        \GPBMetadata\TobaGmtoolCs::initOnce();
        parent::__construct();
    }

}

