<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: TSProtocol.proto

namespace Toba\Tool;

/**
 * Protobuf enum <code>Toba\Tool\ERROR</code>
 */
class ERROR
{
    /**
     * 操作成功
     *
     * Generated from protobuf enum <code>ERR_OK = 0;</code>
     */
    const ERR_OK = 0;
    /**
     * 找不到该玩家
     *
     * Generated from protobuf enum <code>ERR_NULL_PLAYER = 1000;</code>
     */
    const ERR_NULL_PLAYER = 1000;
}

