<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: TSProtocol.proto

namespace Toba\Tool;

/**
 * Protobuf enum <code>Toba\Tool\GMERRORNO</code>
 */
class GMERRORNO
{
    /**
     * Generated from protobuf enum <code>GMERRORNO_ZERO = 0;</code>
     */
    const GMERRORNO_ZERO = 0;
    /**
     *错误代码定义
     *
     * Generated from protobuf enum <code>GMERR_SUCCESS = 1000;</code>
     */
    const GMERR_SUCCESS = 1000;
    /**
     *数据库 错误
     *
     * Generated from protobuf enum <code>GMERR_DB_ERROR = 1001;</code>
     */
    const GMERR_DB_ERROR = 1001;
    /**
     *错误邮件类型
     *
     * Generated from protobuf enum <code>GMERR_MAILTYPE_ERROR = 1005;</code>
     */
    const GMERR_MAILTYPE_ERROR = 1005;
    /**
     * 帐号不能为空
     *
     * Generated from protobuf enum <code>GMERR_NICKNAME_ERROR = 1006;</code>
     */
    const GMERR_NICKNAME_ERROR = 1006;
    /**
     *账号不存在
     *
     * Generated from protobuf enum <code>GMERR_ACCOUNT_ERROR = 1007;</code>
     */
    const GMERR_ACCOUNT_ERROR = 1007;
    /**
     *活动id不存在
     *
     * Generated from protobuf enum <code>GMERR_ACTIVITYID_ERROR = 1008;</code>
     */
    const GMERR_ACTIVITYID_ERROR = 1008;
    /**
     *活动进行中不能修改时间
     *
     * Generated from protobuf enum <code>GMERR_ACTIVITY_RUNNING_ERROR = 1009;</code>
     */
    const GMERR_ACTIVITY_RUNNING_ERROR = 1009;
    /**
     *活动参数错误
     *
     * Generated from protobuf enum <code>GMERR_ACTIVITY_PARAMS_ERROR = 1010;</code>
     */
    const GMERR_ACTIVITY_PARAMS_ERROR = 1010;
    /**
     * 发邮件时，玩家帐号不存在
     *
     * Generated from protobuf enum <code>GMERR_NULL_ACCOUNT_ERROR = 1011;</code>
     */
    const GMERR_NULL_ACCOUNT_ERROR = 1011;
    /**
     *服务器未开放
     *
     * Generated from protobuf enum <code>GMERR_SERVER_ERROR = 1012;</code>
     */
    const GMERR_SERVER_ERROR = 1012;
    /**
     * 登录的不是GM帐号
     *
     * Generated from protobuf enum <code>GMERR_NOTGM_ERROR = 1013;</code>
     */
    const GMERR_NOTGM_ERROR = 1013;
}

