<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: TSProtocol.proto

namespace Toba\Tool;

/**
 * Protobuf enum <code>Toba\Tool\MailType</code>
 */
class MailType
{
    /**
     * 全服邮件
     *
     * Generated from protobuf enum <code>MT_AllServer = 0;</code>
     */
    const MT_AllServer = 0;
    /**
     * 私人邮件
     *
     * Generated from protobuf enum <code>MT_Private = 1;</code>
     */
    const MT_Private = 1;
}

