<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: TSProtocol.proto

namespace Toba\Tool;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>toba.tool.MSG_Tool_Onlines_Respone</code>
 */
class MSG_Tool_Onlines_Respone extends \Google\Protobuf\Internal\Message
{
    /**
     *在线人数
     *
     * Generated from protobuf field <code>uint32 counts = 1;</code>
     */
    private $counts = 0;

    public function __construct() {
        \GPBMetadata\TSProtocol::initOnce();
        parent::__construct();
    }

    /**
     *在线人数
     *
     * Generated from protobuf field <code>uint32 counts = 1;</code>
     * @return int
     */
    public function getCounts()
    {
        return $this->counts;
    }

    /**
     *在线人数
     *
     * Generated from protobuf field <code>uint32 counts = 1;</code>
     * @param int $var
     * @return $this
     */
    public function setCounts($var)
    {
        GPBUtil::checkUint32($var);
        $this->counts = $var;

        return $this;
    }

}

