<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: TSProtocol.proto

namespace Toba\Tool;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>toba.tool.MSG_Tool_Mail_Request</code>
 */
class MSG_Tool_Mail_Request extends \Google\Protobuf\Internal\Message
{
    /**
     * 邮件类型
     *
     * Generated from protobuf field <code>uint32 type = 1;</code>
     */
    private $type = 0;
    /**
     * 玩家id
     *
     * Generated from protobuf field <code>uint32 accountid = 2;</code>
     */
    private $accountid = 0;
    /**
     * 邮件开始生效时间
     *
     * Generated from protobuf field <code>uint32 starttime = 3;</code>
     */
    private $starttime = 0;
    /**
     * 邮件失效时间
     *
     * Generated from protobuf field <code>uint32 endtime = 4;</code>
     */
    private $endtime = 0;
    /**
     * 标题
     *
     * Generated from protobuf field <code>string title = 5;</code>
     */
    private $title = '';
    /**
     * 内容// [格式：物品类型:物品id:物品数量|物品类型:物品id:物品数量...]
     *
     * Generated from protobuf field <code>string content = 6;</code>
     */
    private $content = '';
    /**
     * 奖励信息
     *
     * Generated from protobuf field <code>string award = 7;</code>
     */
    private $award = '';
    /**
     * 公告时署名
     *
     * Generated from protobuf field <code>string signature = 8;</code>
     */
    private $signature = '';

    public function __construct() {
        \GPBMetadata\TSProtocol::initOnce();
        parent::__construct();
    }

    /**
     * 邮件类型
     *
     * Generated from protobuf field <code>uint32 type = 1;</code>
     * @return int
     */
    public function getType()
    {
        return $this->type;
    }

    /**
     * 邮件类型
     *
     * Generated from protobuf field <code>uint32 type = 1;</code>
     * @param int $var
     * @return $this
     */
    public function setType($var)
    {
        GPBUtil::checkUint32($var);
        $this->type = $var;

        return $this;
    }

    /**
     * 玩家id
     *
     * Generated from protobuf field <code>uint32 accountid = 2;</code>
     * @return int
     */
    public function getAccountid()
    {
        return $this->accountid;
    }

    /**
     * 玩家id
     *
     * Generated from protobuf field <code>uint32 accountid = 2;</code>
     * @param int $var
     * @return $this
     */
    public function setAccountid($var)
    {
        GPBUtil::checkUint32($var);
        $this->accountid = $var;

        return $this;
    }

    /**
     * 邮件开始生效时间
     *
     * Generated from protobuf field <code>uint32 starttime = 3;</code>
     * @return int
     */
    public function getStarttime()
    {
        return $this->starttime;
    }

    /**
     * 邮件开始生效时间
     *
     * Generated from protobuf field <code>uint32 starttime = 3;</code>
     * @param int $var
     * @return $this
     */
    public function setStarttime($var)
    {
        GPBUtil::checkUint32($var);
        $this->starttime = $var;

        return $this;
    }

    /**
     * 邮件失效时间
     *
     * Generated from protobuf field <code>uint32 endtime = 4;</code>
     * @return int
     */
    public function getEndtime()
    {
        return $this->endtime;
    }

    /**
     * 邮件失效时间
     *
     * Generated from protobuf field <code>uint32 endtime = 4;</code>
     * @param int $var
     * @return $this
     */
    public function setEndtime($var)
    {
        GPBUtil::checkUint32($var);
        $this->endtime = $var;

        return $this;
    }

    /**
     * 标题
     *
     * Generated from protobuf field <code>string title = 5;</code>
     * @return string
     */
    public function getTitle()
    {
        return $this->title;
    }

    /**
     * 标题
     *
     * Generated from protobuf field <code>string title = 5;</code>
     * @param string $var
     * @return $this
     */
    public function setTitle($var)
    {
        GPBUtil::checkString($var, True);
        $this->title = $var;

        return $this;
    }

    /**
     * 内容// [格式：物品类型:物品id:物品数量|物品类型:物品id:物品数量...]
     *
     * Generated from protobuf field <code>string content = 6;</code>
     * @return string
     */
    public function getContent()
    {
        return $this->content;
    }

    /**
     * 内容// [格式：物品类型:物品id:物品数量|物品类型:物品id:物品数量...]
     *
     * Generated from protobuf field <code>string content = 6;</code>
     * @param string $var
     * @return $this
     */
    public function setContent($var)
    {
        GPBUtil::checkString($var, True);
        $this->content = $var;

        return $this;
    }

    /**
     * 奖励信息
     *
     * Generated from protobuf field <code>string award = 7;</code>
     * @return string
     */
    public function getAward()
    {
        return $this->award;
    }

    /**
     * 奖励信息
     *
     * Generated from protobuf field <code>string award = 7;</code>
     * @param string $var
     * @return $this
     */
    public function setAward($var)
    {
        GPBUtil::checkString($var, True);
        $this->award = $var;

        return $this;
    }

    /**
     * 公告时署名
     *
     * Generated from protobuf field <code>string signature = 8;</code>
     * @return string
     */
    public function getSignature()
    {
        return $this->signature;
    }

    /**
     * 公告时署名
     *
     * Generated from protobuf field <code>string signature = 8;</code>
     * @param string $var
     * @return $this
     */
    public function setSignature($var)
    {
        GPBUtil::checkString($var, True);
        $this->signature = $var;

        return $this;
    }

}

