<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: TSProtocol.proto

namespace Toba\Tool;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>toba.tool.MSG_Tool_SendMail_Request</code>
 */
class MSG_Tool_SendMail_Request extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>.toba.tool.MailInfo mailinfo = 1;</code>
     */
    private $mailinfo = null;

    public function __construct() {
        \GPBMetadata\TSProtocol::initOnce();
        parent::__construct();
    }

    /**
     * Generated from protobuf field <code>.toba.tool.MailInfo mailinfo = 1;</code>
     * @return \Toba\Tool\MailInfo
     */
    public function getMailinfo()
    {
        return $this->mailinfo;
    }

    /**
     * Generated from protobuf field <code>.toba.tool.MailInfo mailinfo = 1;</code>
     * @param \Toba\Tool\MailInfo $var
     * @return $this
     */
    public function setMailinfo($var)
    {
        GPBUtil::checkMessage($var, \Toba\Tool\MailInfo::class);
        $this->mailinfo = $var;

        return $this;
    }

}

