<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: simple.proto

/**
 * Protobuf enum <code>MSGID</code>
 */
class MSGID
{
    /**
     * Generated from protobuf enum <code>MSGID_ZERO = 0;</code>
     */
    const MSGID_ZERO = 0;
    /**
     * Generated from protobuf enum <code>GetServerList = 10001;</code>
     */
    const GetServerList = 10001;
    /**
     * Generated from protobuf enum <code>GetServerOnline = 10002;</code>
     */
    const GetServerOnline = 10002;
    /**
     * Generated from protobuf enum <code>GetUserInfo = 10003;</code>
     */
    const GetUserInfo = 10003;
}

