<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: simple.proto

/**
 * 错误码
 *
 * Protobuf enum <code>ERRNO</code>
 */
class ERRNO
{
    /**
     * Generated from protobuf enum <code>ERR_OK = 0;</code>
     */
    const ERR_OK = 0;
    /**
     * 服务器不存在
     *
     * Generated from protobuf enum <code>ERR_SERVER_NOTFOUND = 10001;</code>
     */
    const ERR_SERVER_NOTFOUND = 10001;
}

