<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: simple.proto

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * 获取服务器在线人数
 *
 * Generated from protobuf message <code>MSG_GetServerOnline_Request</code>
 */
class MSG_GetServerOnline_Request extends \Google\Protobuf\Internal\Message
{
    /**
     * 服务器名
     *
     * Generated from protobuf field <code>string serverName = 1;</code>
     */
    private $serverName = '';

    public function __construct() {
        \GPBMetadata\Simple::initOnce();
        parent::__construct();
    }

    /**
     * 服务器名
     *
     * Generated from protobuf field <code>string serverName = 1;</code>
     * @return string
     */
    public function getServerName()
    {
        return $this->serverName;
    }

    /**
     * 服务器名
     *
     * Generated from protobuf field <code>string serverName = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setServerName($var)
    {
        GPBUtil::checkString($var, True);
        $this->serverName = $var;

        return $this;
    }

}

